# Site settings
title: GameLost
header-img: "img/autumn2.jpg"
tagline: ""
description: "DisturbanceN"
baseurl: ""
url: "http://disturbancen.com"
#url: "http://localhost:4000"

# About/contact
owner:
  name: "Maxx78"
  email: 405022026@qq.com
  bio: "测试一下"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: DisturbanceN
twitter_username: DisturbanceN
github_username: DisturbanceN
facebook_username: DisturbanceN
weibo_username: DisturbanceN
zhihu_username: DisturbanceN

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
relative_permalinks: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "DisturbanceN"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name : Azeril
  disqus :
      short_name : Azeril

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation